[[quote]]
quote = "I want to continue existing in this world! My life is worth living here!"
speaker = "Shinji Ikari"

[[quote]]
quote = "I mustn't run away. I mustn't run away. I mustn't run away."
speaker = "Shinji Ikari"

[[quote]]
quote = "Understanding one hundred percent of everything is impossible. That's what makes life so interesting."
speaker = "Ryoji Kaji"

[[quote]]
quote = "People who know what pain is are kinder to others because of it. That's not the same thing as being weak."
speaker = "Ryoji Kaji"

[[quote]]
quote = "If I ever get to see you again, I'll say the words I wasn't able to say eight years ago. Bye."
speaker = "Ryoji Kaji"

[[quote]]
quote = "There are as many truths as there are people."
speaker = "Ryoji Kaji"

[[quote]]
quote = "You don't deserve to be loved because you don't even love yourself."
speaker = "Asuka Langley Soryu"

[[quote]]
quote = "You're all you have and you never even learned to like yourself."
speaker = "Asuka Langley Soryu"

[[quote]]
quote = "I'll think for myself and I'll live for myself."
speaker = "Asuka Langley Soryu"

[[quote]]
quote = "As long as the Sun, the Moon, and the Earth exist, everything will be alright."
speaker = "Yui Ikari"

[[quote]]
quote = "Is this enough? Then that's good for you."
speaker = "Yui Ikari"

[[quote]]
quote = "Anywhere can be a paradise, as long as you have the will to live."
speaker = "Yui Ikari"

[[quote]]
quote = "One who hates himself cannot love, he cannot place his trust in another."
speaker = "Rei Ayanami"

[[quote]]
quote = "That's because you thought that everyone else felt the same as you do."
speaker = "Rei Ayanami"

[[quote]]
quote = "Mankind hates the darkness, so he scrapes away at the edges of it with fire."
speaker = "Rei Ayanami"

[[quote]]
quote = "Sometimes you need a little wishful thinking just to keep on living."
speaker = "Misato Katsuragi"

[[quote]]
quote = "Giving up halfway is worse than never trying at all."
speaker = "Misato Katsuragi"

[[quote]]
quote = "Miracles aren't just something that happen, they're something you make happen."
speaker = "Misato Katsuragi"

[[quote]]
quote = "The only person who can sympathise with you and understand you, is you."
speaker = "Misato Katsuragi"

[[quote]]
quote = "Acts of men are better than acts of God."
speaker = "Misato Katsuragi"

[[quote]]
quote = "Pain is something man must carry in his heart, and since the heart feels pain so easily, some believe that life is pain."
speaker = "Kaworu Nagisa"

[[quote]]
quote = "Death may be the only absolute freedom there is."
speaker = "Kaworu Nagisa"

[[quote]]
quote = "Man cannot erase this sadness, because all men are fundamentally alone."
speaker = "Kaworu Nagisa"

[[quote]]
quote = "Fate will surely guide you."
speaker = "Kaworu Nagisa"

[[quote]]
quote = "Your truth can be changed simply by the way you accept it. That's how fragile the truth for a human is."
speaker = "Kozo Fuyutsuki"

[[quote]]
quote = "Mankind's greatest fear is mankind itself."
speaker = "Gendo Ikari"

[[quote]]
quote = "The fate of destruction is also the joy of rebirth."
speaker = "Gendo Ikari"
